WEKINATOR 2 SK-LEARN 2 ARDUINO

In [33]:
from sklearn.neural_network import MLPRegressor
X = [[0., 0.], [1., 1.], [50., 80.], [100., 200.], [300., 500.], [800., 1023.]]
y = [[50., 50.], [60., 80.], [100., 120.], [230., 280.], [320., 400.], [800., 1023.]]
#y = [[0., 0.], [1., 1.], [60., 55.], [150., 130.], [400., 370.], [900., 840.]]
clf = MLPRegressor(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(5, 3), random_state=1, activation='identity')

clf.fit(X, y)                         
print(clf.loss_)



607.68314288


In [31]:
clf.predict([[0., 0.], [2., 2.], [40.,38.],[229.,56.], [289., 400.], [908., 1002.], [1023., 1023.]])

array([[   64.42915001,    75.84575488],
       [   66.1583957 ,    78.1111456 ],
       [   98.68212428,   120.86089381],
       [  233.71500585,   309.91656328],
       [  332.72780102,   419.43820325],
       [  865.1078566 ,  1118.08888975],
       [  948.93832241,  1234.59310857]])

In [25]:
[coef.shape for coef in clf.coefs_]

[(2, 5), (5, 3), (3, 2)]

In [26]:
C = clf.coefs_
for i in range(len(C)):
    print("C[%i]"%i)
    print(C[i])

print("\n")

B = clf.intercepts_
for i in range(len(B)):
    print("B[%i]"%i)
    print(B[i])

C[0]
[[ 0.88934223  0.41521056  1.11369377  0.11599794 -0.55886764]
 [-2.02501785  0.04405254 -3.52180649 -0.65712574  0.84774683]]
C[1]
[[ 2.35199952 -1.39947877  1.01215464]
 [ 1.5716492  -1.09810635  0.41401113]
 [ 0.52843942 -0.92920834  1.05723995]
 [ 0.05157508  2.09270307 -2.52975937]
 [-1.43533716 -1.72739091  2.47718292]]
C[2]
[[ 1.14884872  1.24285042]
 [ 2.3818666   2.21076432]
 [-0.7363229  -1.37112853]]


B[0]
[-1.75530443 -2.35604453 -2.40015902  3.1477055  -3.28105536]
B[1]
[-1.36582696  1.85161513 -1.8918131 ]
B[2]
[ 2.79436251  3.62174779]


In [27]:
import numpy as np
def weight_matrix(clf):
    C = clf.coefs_
    B = clf.intercepts_
    W = []
    for i in range(len(C)):
        W.append(np.vstack([C[i], B[i]]))
    return W

def print_4_arduino(W):
    for i in range(len(W)):
        print("W[%i]"%i)
        print("{", end='')
        W_ = np.transpose(W[i])
        for j in range(len(W_)):
            print("{", end='')
            for k in range(len(W_[j])):
                print(str(W_[j][k]), end='')
                if (k!=len(W_[j])-1):
                    print(", ", end='')
            print("}", end='')
            if (j!=len(W_)-1):
                print(", ")
        print("};")
        print()

W = weight_matrix(clf)
print_4_arduino(W)
print([coef.shape for coef in W])

W[0]
{{0.889342232486, -2.02501785293, -1.7553044319}, 
{0.415210555563, 0.0440525416446, -2.35604452887}, 
{1.11369377015, -3.52180648623, -2.40015902002}, 
{0.115997940612, -0.657125744289, 3.14770549941}, 
{-0.558867640679, 0.847746828527, -3.2810553599}};

W[1]
{{2.35199951658, 1.57164920226, 0.528439423835, 0.0515750809269, -1.43533715784, -1.36582695526}, 
{-1.3994787673, -1.09810634784, -0.929208336666, 2.09270307458, -1.72739091252, 1.85161512769}, 
{1.01215464252, 0.414011132713, 1.05723995165, -2.52975936923, 2.47718291903, -1.89181310214}};

W[2]
{{1.14884871817, 2.38186659723, -0.736322896248, 2.79436251316}, 
{1.24285042499, 2.2107643201, -1.37112853368, 3.62174778884}};

[(3, 5), (6, 3), (4, 2)]


In [28]:
clf.predict([[0.,1023.]])

array([[ 234.21625958,  225.54926357]])

In [29]:
X = np.array([91,82,1])
W_1 = [[0.0439705348107, -0.550473547515, -0.0622377884909 ], 
[0.764552457062, -0.44443668827, 0.471115318049 ], 
[-1.19337941334, -0.735254200088, -0.383947108724 ], 
[-0.400170870905, 0.154518984432, 0.564626658027 ], 
[-0.727440202957, -0.419977952043, -0.744249834135 ]];
print(np.matmul(W_1,X))

W_1_ = [[round(elm,2)for elm in W_1[idx]]for idx in range(len(W_1))]
print(np.matmul(W_1_,X))
W_1_



[ -41.19975002   33.60158047 -169.27231813  -23.18036587 -101.37950037]
[ -41.52   33.55 -169.35  -23.54 -101.61]


[[0.04, -0.55, -0.06],
 [0.76, -0.44, 0.47],
 [-1.19, -0.74, -0.38],
 [-0.4, 0.15, 0.56],
 [-0.73, -0.42, -0.74]]

In [30]:
import arff

ImportError: No module named 'arff'